#ifndef MY_CREDENTIALS_H
#define MY_CREDENTIALS_H
// WiFi credentials
#define WIFI_SSID_DEFINED "Your_WiFi_SSID"
#define WIFI_PASSWORD_DEFINED "Your_WiFi_PASSWORD"
#define WIFI_HOTSPOT_MODE_SSID_DEFINED "WiFi_SSID"
#define WIFI_HOTSPOT_MODE_PASSWORD_DEFINED "DEFINED_PASSWORD"
#endif // MY_CREDENTIALS_H